import Head from "next/head";
import { CategoryInterface } from "@/components/CategoryCard/CategoryCard";
import CategoriesList from "@/components/CategoriesList/CategoriesList";
import { GetStaticProps } from "next";
import { FC } from "react";
import Logo from "@/components/LogoBanner/LogoBanner";
import { CompanyInterface } from "@/components/CompanyDetails/CompanyDetails";

interface Props {
  menu: CategoryInterface[];
  company: CompanyInterface;
}

const Home: FC<Props> = ({ menu, company }) => {
  return (
    <>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Logo company={company} />
        <CategoriesList menu={menu} company={company} />
      </main>
    </>
  );
};
export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const resCompany = await fetch(`https://nomad-cloud.in/api/companie`);
  const resMenu = await fetch(`https://nomad-cloud.in/api/menu`);

  const company = await resCompany.json();
  const menu = await resMenu.json();

  return {
    props: {
      company,
      menu,
    },
    // revalidate: 60 * 60 * 24,
  };
};
