import ProductTemplate from "@/components/templates/ProductTemplate/ProductTemplate";
import { MainContext } from "@/context/MainContext";
import { CategoryInterface } from "@/interfaces/CategoryInterface";
import { CompanyInterface } from "@/interfaces/CompanyInterface";
import { ProductsInterface } from "@/interfaces/ProductsInterface";
import axios from "axios";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import React, { FC, useContext, useEffect } from "react";

interface Props {
  products: ProductsInterface[];
  categories: CategoryInterface[];
  company: CompanyInterface;
}

const CategoryPage: FC<Props> = ({ products, categories, company }) => {
  const {
    setProducts,
    setCategories,
    setCompany,
    setSelectedCategoryId,
    selectedCategoryId,
  } = useContext(MainContext);

  useEffect(() => {
    setProducts(products);
    setCompany(company);
    setCategories(categories);
    setSelectedCategoryId(
      selectedCategoryId || categories
        ? selectedCategoryId || categories[0].id
        : null
    );
  }, []);

  return (
    <>
      <Head>
        <title>Desserts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/menu.svg" />
      </Head>
      <main>
        <ProductTemplate />
      </main>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const API_URL = process.env.API_URL;
  const products = await axios.get(`${API_URL}/categorieForProducts`);
  const paths = products.data?.map((p: ProductsInterface) => ({
    params: {
      id: p.id.toString(),
    },
  }));
  return {
    paths,
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const API_URL = process.env.API_URL;

  if (params && params.id) {
    const products = await axios.get(
      `${API_URL}/categorieForProducts/${params.id}`
    );
    const company = await axios.get(`${API_URL}/companie`);
    const categories = await axios.get(`${API_URL}/menu`);

    if (Object.keys(products).length === 0) {
      return {
        notFound: true,
      };
    }

    return {
      props: {
        products: products.data,
        company: company.data,
        categories: categories.data,
      },
      revalidate: 1,
    };
  }

  return {
    notFound: true,
  };
};

export default CategoryPage;
